name: Calculate Inference Pipeline
on: push                                         

permissions:
  contents: read

jobs:
  matrix-inference:
    strategy:
      matrix:
        numerator: [1,2,3,4,5]
    uses: ./.github/workflows/instance-inference.yml
    with:
      numerator: ${{ matrix.numerator }}
      denominator: 5
    secrets: inherit

    
#   partition-1:
#     uses: ./.github/workflows/instance-inference.yml
#     with:
#       numerator: 1
#       denominator: 2
#     secrets: inherit

#   partition-2:
#     uses: ./.github/workflows/instance-inference.yml
#     with:
#       numerator: 2
#       denominator: 2
#     secrets: inherit
