name: Calculate Inference Pipeline
on: push                                         

permissions:
  contents: read

env:
  MODEL_ID: ${{ github.event.repository.name }}
  SHA: ${{ github.sha }}

jobs:
  partition-1:
    runs-on: ubuntu-latest
    steps:
      - name: Perform Inference
        uses: ./.github/actions/perform-inference
        with:
          numerator: 1
          denominator: 2
  
  partition-2:
    runs-on: ubuntu-latest
    steps:
      - name: Perform Inference
        uses: ./.github/actions/perform-inference
        with:
          numerator: 2
          denominator: 2
