name: Calculate Inference Pipeline
on: push                                         

permissions:
  contents: read

jobs:
  partition-1:
    uses: ./.github/workflows/instance-inference.yml
    with:
      numerator: 1
      denominator: 2
    secrets: inherit

  partition-2:
    uses: ./.github/workflows/instance-inference.yml
    with:
      numerator: 2
      denominator: 2
    secrets: inherit
